version: "3"

services:
  
  download-server:
    image: nginx:latest
    container_name: download-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    ports:
      - "85:80"
    volumes:
      - ../download/conf.d:/etc/nginx/conf.d
      - ../download/resources:/resources


  etracs25-server:
    image: ramesesinc/etracs25-server-municipality:255.02.003
    container_name: etracs25-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    env_file:
      - ./env.conf
      - ../_custom/env.conf
    ports:
      - "8060:8060"
      - "8061:8061"
      - "8070:8070"
      - "8080:8080"
    volumes:
      - ./modules:/apps/etracs25/modules
      - ../_res/connections:/apps/etracs25/connections/ext
      - ../_custom/lgu-module:/apps/etracs25/modules/ext/lgu-module

      - ./dev_modules/rptis:/rptis
      - ./dev_modules/rptis/etracs_rptis.conf:/apps/etracs25/modules.conf.d/etracs_rptis.conf

      - ./dev_modules/treasury/rameses-gov-treasury-services.jar:/services/modules/etracs/rameses-gov-treasury-services.jar
      - ./dev_modules/treasury/rameses-gov-treasury-report-services.jar:/services/modules/etracs/rameses-gov-treasury-report-services.jar
      - ./dev_modules/treasury/rameses-gov-treasury-tool-services.jar:/services/modules/etracs/rameses-gov-treasury-tool-services.jar
